
# Api gateway
@api = https://thesisapi.ddns.net

### At first, create an account
POST {{api}}/identity/sign-up
Content-Type: application/json; charset=utf-8

{
  "email": "admin10@wp.pl",
  "password": "1qaz2wsx",
  "role": "admin"
}

### Authenticate and grab the access token
# @name sign_in
POST {{api}}/identity/sign-in
Content-Type: application/json

{
  "email": "mateusz2@wp.pl",
  "password": "1qaz"
}

### Get your identity account details
# @name me
@accessToken = {{sign_in.response.body.$.accessToken}}
@refreshToken = {{sign_in.response.body.$.refreshToken}}
GET {{api}}/identity/me
Authorization: Bearer {{accessToken}}

### renew access token
POST {{api}}/identity/refresh-tokens/use
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### Complete the user registration process
@userId = {{me.response.body.$.id}}
POST {{api}}/users
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "pseudonym": "mateusz2",
}

### Get your user account details
GET {{api}}/users/me
Authorization: Bearer {{accessToken}}


### Add your GPS location
# @name add_location
POST {{api}}/locations
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "latitude" : 50.003,
  "longitude" : 20.003,
  "accuracy" : 9
}


### Add new route
# @name add_route
POST {{api}}/routes
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Casual running 6",
  "description": "",
  "difficulty": "black",
  "activityKind": 7,
  "points":[
    {
      "order": 3,
      "latitude": 80.003,
      "longitude": -20.003,
      "radius": 30
    },
    {
      "order": 2,
      "latitude": 80.002,
      "longitude": -20.002,
      "radius": 10
    },
    {
      "order": 1,
      "latitude": 80.001,
      "longitude": -20.001,
      "radius": 10
    },
    {
      "order": 0,
      "latitude": 80.000,
      "longitude": -20.000,
      "radius": 10
    }
  ]
}

### Get route
# @name get_route
@getRoute = {{add_route.response.headers.Location}}
GET {{api}}/routes/{{getRoute}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### Get other routes //?page=1&topLeftLatitude=50&bottomRightLatitude=0&topLeftLongitude=0&bottomRightLongitude=30&resultsPerPage=12
# @name get_routes
GET {{api}}/routes?OnlyNew=true
Authorization: Bearer {{accessToken}}
Content-Type: application/json


### Change route status to accepted
@routeId = {{get_route.response.body.$.id}}
PUT {{api}}/routes/{{routeId}}/status/Accepted
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{

}

### Create run
# @name create_run
POST {{api}}/runs
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "runId": "11111111-dcbb-4708-96b7-0a8cc5de140a",
  "userId" : "a713d910-dcbb-4708-96b7-0a8cc5de140a",
  "routeId": "{{routeId}}",
  "latitude": 50.0,
  "longitude": 20.0,
  "accuracy": 30
}

### Get my score
GET {{api}}/scores/{{userId}}
Content-Type: application/json

### Get all users score
GET {{api}}/scores/
Content-Type: application/json

### Get my achievements
GET {{api}}/achievements/{{userId}}
Content-Type: application/json


### Get ranking
GET {{api}}/runs?RouteId=d92a7e97-0895-40a5-8428-e03fc02e0559&orderBy=time&sortOrder=asc
Content-Type: application/json

### Get route resources
GET {{api}}/resources?routeId=2fd8d036-727a-4e4e-88ab-9fd383752471

### Create route resource
POST {{api}}/resources
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "routeId": "2fd8d036-727a-4e4e-88ab-9fd383752471",
  "text" : "meeep."
}
