
# Api gateway
@api = http://ubuntu-docker-host:5009 

### At first, create an account
POST {{api}}/identity/sign-up
Content-Type: application/json

{
  "email": "scenario-user1@domain.com",
  "password": "secret",
  "role": "user"
}

### Authenticate and grab the access token
# @name sign_in
POST {{api}}/identity/sign-in
Content-Type: application/json

{
  "email": "scenario-user1@domain.com",
  "password": "secret"
}

### Get your identity account details
# @name me
@accessToken = {{sign_in.response.body.$.accessToken}}
@refreshToken = {{sign_in.response.body.$.refreshToken}}
GET {{api}}/identity/me
Authorization: Bearer {{accessToken}}



### Complete the user registration process
@userId = {{me.response.body.$.id}}
POST {{api}}/users
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "fullName": "John Doe",
  "address": "New York"
}

### Get your user account details
GET {{api}}/users/me
Authorization: Bearer {{accessToken}}


### Add your GPS location
# @name add_location
POST {{api}}/locations
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "latitude" : 50.123,
  "longitude" : 20.123,
  "accuracy" : 150
}


### Add new route
# @name add_route
POST {{api}}/routes
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "latitude" : 50.123,
  "longitude" : 20.123,
  "accuracy" : 150
}